FROM registry.fedoraproject.org/fedora:latest@sha256:53395873897c32f086e852d56eb11aa67ae64ae1bd9ece348bc253bef7d5cca1

COPY mock-wrapper /usr/bin

RUN dnf install -y mock rpmdevtools rpkg copr-cli rpmlint && dnf clean all

ENTRYPOINT ["/usr/bin/mock-wrapper"]
